-- bl_residuals.sql [E09]
--
-- Code generated by internal/detect/anomaly/sql/gen from residuals.go.tmpl;
-- DO NOT EDIT. Correr `go generate ./internal/detect/anomaly/jobs/...` para
-- regenerar.
--
-- T-334 (E09-T12) -- E09 §4.8.4, §4.6.5, §4.11.1 · E00b D-10, D-5, D-35 ·
-- E00c C-2 · E09 §9.7 N25 · E09 §5.10.
--
-- J5: la fila ancha por entidad y ventana de 5 minutos con el z de las
-- cinco métricas (E09 §4.8.4) -- el insumo de anomaly.level_shift, de J6
-- (T-337/338) y del oráculo (T-346). Las cinco expresiones de resolución
-- de jerarquía + z son IDÉNTICAS salvo el nombre de la métrica -- esa
-- repetición es lo que genera esta plantilla, para que las cinco no se
-- puedan desincronizar a mano (criterio de aceptación de T-334).
--
-- La resolución de jerarquía (§4.6.5) es la misma que
-- anomaly.volume_spike usará en fase 3 (E09 §4.11.1, transcripta acá
-- porque J5 es quien primero la necesita): L2 (dict_bl_profile del
-- entity_kind real) → L1 (nivel de la entidad + forma de su cohorte) →
-- L0 (nivel de la entidad + forma global) → ninguno (mu_eff = NaN, z
-- también sale NaN y se propaga -- J5 no filtra por isFinite: eso es del
-- DETECTOR que consume evidence, no de esta bitácora).
--
-- offset_log/sigma_scale salen de isp.dict_bl_thresholds keyeado por
-- ('anomaly.level_shift', métrica): es el ÚNICO detector real que lee
-- bl_residuals directamente (anomaly.level_shift, CUSUM de z_pps,
-- E09 §4.11.3) -- volume_spike/fanout_spike recalculan su propio z inline
-- con SU PROPIO detector_id y no pasan por esta tabla. J6 (T-337/338)
-- tiene que escribir bl_thresholds con esa misma clave para que la
-- calibración de J5 no quede huérfana; hasta entonces, dictGetOrDefault
-- degrada a offset_log=0/sigma_scale=1 (equivalente a la fórmula previa a
-- D-12) sin ningún error.
--
-- mad_log_floor NO es SEC_DETECT_BASELINE_* (E09 §5.8 no lo lista, D-29,
-- N8): es un Param del detector, igual que en volume_spike/fanout_spike;
-- este job lo declara con el mismo default de §4.6.4 (0.20).
--
-- resolveEntity idéntica carácter a carácter a bl_cohorts.sql/bl_level.sql
-- (E09 §4.3).
--
-- D-10/C-2: la observación lee v_agg_src_1m_flat, que resuelve los
-- estados con finalizeAggregation FILA A FILA y no lleva GROUP BY -- las
-- partes de la MISMA clave se colapsan ACÁ (NIVEL 1) antes de tomar
-- cualquier max(): un max(pps) directo sobre las partes sin colapsar
-- devuelve el pps de media clave. Entre partes de la misma clave, las
-- cardinalidades se re-agregan con max(), nunca con sum() (E03 §4.6.1).
-- _flat tampoco expone pps/bps derivados: se calculan sobre los 60 s de
-- la ventana, igual que v_agg_src_1m.
--
-- G-4a/N19: el alias de customer_id en NIVEL 1 tiene que ser
-- customer_id_any -- con AS customer_id los tres any(customer_id) de
-- resolveEntity se leerían como any(any(customer_id)) e ILLEGAL_AGGREGATION.
--
-- Parámetros: {from:DateTime} {to:DateTime} {tz:String} {v6_bits:UInt8}
-- {mad_log_floor:Float64} {residual_min_pps:Float64}
-- {residual_min_uniq_dst:UInt32} {residual_max_entities:UInt32}

INSERT INTO isp.bl_residuals
    (window_start, entity_kind, entity_key, slot, level_used, top_src_ip,
     z_pps, z_bps, z_uniq_dst_ips, z_uniq_dst_ports, z_flows,
     obs_pps, obs_bps, obs_uniq_dst_ips, obs_uniq_dst_ports, obs_flows,
     exp_pps, exp_bps, exp_uniq_dst_ips, exp_uniq_dst_ports, exp_flows,
     quality, sampling_max, minutes_seen)
SELECT
    window_start, entity_kind, entity_key, slot,
    -- Alias explícito en las CINCO columnas que la SELECT no nombra igual
    -- que la tabla (level_used/z_*/quality): T-346 (E09-T24) corre este
    -- mismo SELECT, recortado del INSERT, standalone vía QueryContext
    -- para alimentar el oráculo sin releer bl_residuals -- sin el alias
    -- explícito, ClickHouse le pone a la columna el texto de la expresión
    -- entera (p. ej. "toFloat32(z_pps)"), que solo importaba antes porque
    -- un INSERT ... SELECT liga por POSICIÓN, nunca por nombre; una
    -- SELECT standalone si necesita el nombre real.
    CAST(level_used_num, 'Enum8(''none''=0,''entity''=1,''cohort''=2,''global''=3)') AS level_used,
    top_src_ip,
    toFloat32(z_pps) AS z_pps, toFloat32(z_bps) AS z_bps, toFloat32(z_uniq_dst_ips) AS z_uniq_dst_ips,
    toFloat32(z_uniq_dst_ports) AS z_uniq_dst_ports, toFloat32(z_flows) AS z_flows,
    obs_pps, obs_bps, obs_uniq_dst_ips, obs_uniq_dst_ports, obs_flows,
    exp_pps, exp_bps, exp_uniq_dst_ips, exp_uniq_dst_ports, exp_flows,
    toFloat32(quality_avg) AS quality, sampling_max, toUInt8(minutes_seen) AS minutes_seen
FROM
(
    WITH
        toTimeZone({from:DateTime}, {tz:String})                                 AS lstart,
        toDate(lstart)                                                          AS lday,
        dictGetOrDefault('isp.dict_bl_calendar', 'daytype', tuple(lday),
                         if(toDayOfWeek(lday) >= 6, toUInt8(1), toUInt8(0)))     AS daytype,
        toUInt8(daytype * 24 + toHour(lstart))                                  AS slot,
        -- ══ NIVEL 2: de (minuto, IP) a entidad ══════════════════════════════
        obs AS
        (
            SELECT
                entity_kind,
                entity_key,
                argMax(src_ip, pps_min)                                        AS top_src_ip,
                any(customer_id_any)                                           AS customer_id,
                max(pps_min)                                                   AS obs_pps,
                max(bps_min)                                                   AS obs_bps,
                max(uniq_dst_ips_min)                                          AS obs_uniq_dst_ips,
                max(uniq_dst_ports_min)                                        AS obs_uniq_dst_ports,
                sum(flows_min)                                                 AS obs_flows,
                max(sampling_max_min)                                         AS sampling_max,
                uniqExact(window_start)                                        AS minutes_seen
            FROM
            (
                -- ══ NIVEL 1: colapsar las partes de _flat ═══════════════════
                SELECT
                    window_start,
                    src_ip,
                    any(customer_id)                                           AS customer_id_any,
                    multiIf(any(customer_id) != '', toUInt8(2),
                            src_ip <= toIPv6('::ffff:255.255.255.255'), toUInt8(3),
                            toUInt8(4))                                        AS entity_kind,
                    multiIf(any(customer_id) != '', any(customer_id),
                            src_ip <= toIPv6('::ffff:255.255.255.255'), isp_ip_str(src_ip),
                            isp_ip_str(tupleElement(IPv6CIDRToRange(src_ip, {v6_bits:UInt8}), 1))
                                || '/' || toString({v6_bits:UInt8}))            AS entity_key,
                    sum(packets)     / 60.0                                    AS pps_min,
                    sum(bytes) * 8.0 / 60.0                                    AS bps_min,
                    sum(flows)                                                 AS flows_min,
                    max(uniq_dst_ips)                                          AS uniq_dst_ips_min,
                    max(uniq_dst_ports)                                        AS uniq_dst_ports_min,
                    max(sampling_max)                                          AS sampling_max_min
                FROM isp.v_agg_src_1m_flat
                WHERE window_start >= {from:DateTime} AND window_start < {to:DateTime}
                  AND flow_dir  = 'outbound'
                  AND src_scope = 'customer'
                GROUP BY window_start, src_ip
            )
            GROUP BY entity_kind, entity_key
        )
    SELECT
        {from:DateTime}                                                        AS window_start,
        o.entity_kind                                                          AS entity_kind,
        o.entity_key                                                           AS entity_key,
        slot,
        o.top_src_ip                                                           AS top_src_ip,
        o.obs_pps                                                              AS obs_pps,
        o.obs_bps                                                              AS obs_bps,
        o.obs_uniq_dst_ips                                                     AS obs_uniq_dst_ips,
        o.obs_uniq_dst_ports                                                   AS obs_uniq_dst_ports,
        o.obs_flows                                                            AS obs_flows,
        o.sampling_max                                                        AS sampling_max,
        o.minutes_seen                                                        AS minutes_seen,

        -- ═══ Resolución de jerarquía + z de pps (E09 §4.6.5) ═══════════════
        dictGetOrDefault('isp.dict_bl_profile', ('mu_log', 'mad_log', 'ready', 'quality', 'n_eff'),
                         (o.entity_kind, o.entity_key, 'pps', slot),
                         (toFloat64(0), toFloat64(0), toUInt8(0), toFloat32(0), toUInt32(0)))  AS p2_pps,
        dictGetOrDefault('isp.dict_bl_entity', ('cohort', 'level_log', 'state', 'quality'),
                         (o.entity_kind, o.entity_key, 'pps'),
                         ('unknown', toFloat64(0), toUInt8(0), toFloat32(0)))                   AS en_pps,
        dictGetOrDefault('isp.dict_bl_profile', ('shape_log', 'mad_log', 'ready', 'quality', 'n_eff'),
                         (toUInt8(1), en_pps.1, 'pps', slot),
                         (toFloat64(0), toFloat64(0), toUInt8(0), toFloat32(0), toUInt32(0)))   AS p1_pps,
        dictGetOrDefault('isp.dict_bl_profile', ('shape_log', 'mad_log', 'ready', 'quality', 'n_eff'),
                         (toUInt8(0), '', 'pps', slot),
                         (toFloat64(0), toFloat64(0), toUInt8(0), toFloat32(0), toUInt32(0)))   AS p0_pps,
        dictGetOrDefault('isp.dict_bl_thresholds', ('offset_log', 'sigma_scale'),
                         ('anomaly.level_shift', 'pps'),
                         (toFloat64(0), toFloat64(1)))                                          AS th_pps,
        multiIf(p2_pps.3 = 1 AND en_pps.3 != 4, p2_pps.1,
                p1_pps.3 = 1 AND en_pps.3 IN (2, 5), en_pps.2 + p1_pps.1,
                p0_pps.3 = 1 AND en_pps.3 IN (2, 5), en_pps.2 + p0_pps.1,
                CAST(nan, 'Float64'))                                                           AS mu_eff_pps,
        greatest(1.4826 * multiIf(p2_pps.3 = 1 AND en_pps.3 != 4, p2_pps.2,
                                  p1_pps.3 = 1, p1_pps.2,
                                  p0_pps.2),
                 {mad_log_floor:Float64})                                                       AS sigma_hat_pps,
        sigma_hat_pps * th_pps.2                                                          AS sigma_use_pps,
        multiIf(p2_pps.3 = 1 AND en_pps.3 != 4, toUInt8(1),
                p1_pps.3 = 1, toUInt8(2),
                p0_pps.3 = 1, toUInt8(3),
                toUInt8(0))                                                                     AS level_used_pps,
        multiIf(p2_pps.3 = 1 AND en_pps.3 != 4, p2_pps.4,
                p1_pps.3 = 1, p1_pps.4 * 0.7,
                p0_pps.4 * 0.5)                                                              AS quality_eff_pps,
        (log1p(o.obs_pps) - th_pps.1 - mu_eff_pps) / sigma_use_pps                  AS z_pps,
        -- ClickHouse no tiene expm1(): exp(x)-1 (E09 §4.6.5, baseline_value).
        exp(mu_eff_pps + th_pps.1) - 1                                                    AS exp_pps,

        -- ═══ Resolución de jerarquía + z de bps (E09 §4.6.5) ═══════════════
        dictGetOrDefault('isp.dict_bl_profile', ('mu_log', 'mad_log', 'ready', 'quality', 'n_eff'),
                         (o.entity_kind, o.entity_key, 'bps', slot),
                         (toFloat64(0), toFloat64(0), toUInt8(0), toFloat32(0), toUInt32(0)))  AS p2_bps,
        dictGetOrDefault('isp.dict_bl_entity', ('cohort', 'level_log', 'state', 'quality'),
                         (o.entity_kind, o.entity_key, 'bps'),
                         ('unknown', toFloat64(0), toUInt8(0), toFloat32(0)))                   AS en_bps,
        dictGetOrDefault('isp.dict_bl_profile', ('shape_log', 'mad_log', 'ready', 'quality', 'n_eff'),
                         (toUInt8(1), en_bps.1, 'bps', slot),
                         (toFloat64(0), toFloat64(0), toUInt8(0), toFloat32(0), toUInt32(0)))   AS p1_bps,
        dictGetOrDefault('isp.dict_bl_profile', ('shape_log', 'mad_log', 'ready', 'quality', 'n_eff'),
                         (toUInt8(0), '', 'bps', slot),
                         (toFloat64(0), toFloat64(0), toUInt8(0), toFloat32(0), toUInt32(0)))   AS p0_bps,
        dictGetOrDefault('isp.dict_bl_thresholds', ('offset_log', 'sigma_scale'),
                         ('anomaly.level_shift', 'bps'),
                         (toFloat64(0), toFloat64(1)))                                          AS th_bps,
        multiIf(p2_bps.3 = 1 AND en_bps.3 != 4, p2_bps.1,
                p1_bps.3 = 1 AND en_bps.3 IN (2, 5), en_bps.2 + p1_bps.1,
                p0_bps.3 = 1 AND en_bps.3 IN (2, 5), en_bps.2 + p0_bps.1,
                CAST(nan, 'Float64'))                                                           AS mu_eff_bps,
        greatest(1.4826 * multiIf(p2_bps.3 = 1 AND en_bps.3 != 4, p2_bps.2,
                                  p1_bps.3 = 1, p1_bps.2,
                                  p0_bps.2),
                 {mad_log_floor:Float64})                                                       AS sigma_hat_bps,
        sigma_hat_bps * th_bps.2                                                          AS sigma_use_bps,
        multiIf(p2_bps.3 = 1 AND en_bps.3 != 4, toUInt8(1),
                p1_bps.3 = 1, toUInt8(2),
                p0_bps.3 = 1, toUInt8(3),
                toUInt8(0))                                                                     AS level_used_bps,
        multiIf(p2_bps.3 = 1 AND en_bps.3 != 4, p2_bps.4,
                p1_bps.3 = 1, p1_bps.4 * 0.7,
                p0_bps.4 * 0.5)                                                              AS quality_eff_bps,
        (log1p(o.obs_bps) - th_bps.1 - mu_eff_bps) / sigma_use_bps                  AS z_bps,
        -- ClickHouse no tiene expm1(): exp(x)-1 (E09 §4.6.5, baseline_value).
        exp(mu_eff_bps + th_bps.1) - 1                                                    AS exp_bps,

        -- ═══ Resolución de jerarquía + z de uniq_dst_ips (E09 §4.6.5) ═══════════════
        dictGetOrDefault('isp.dict_bl_profile', ('mu_log', 'mad_log', 'ready', 'quality', 'n_eff'),
                         (o.entity_kind, o.entity_key, 'uniq_dst_ips', slot),
                         (toFloat64(0), toFloat64(0), toUInt8(0), toFloat32(0), toUInt32(0)))  AS p2_uniq_dst_ips,
        dictGetOrDefault('isp.dict_bl_entity', ('cohort', 'level_log', 'state', 'quality'),
                         (o.entity_kind, o.entity_key, 'uniq_dst_ips'),
                         ('unknown', toFloat64(0), toUInt8(0), toFloat32(0)))                   AS en_uniq_dst_ips,
        dictGetOrDefault('isp.dict_bl_profile', ('shape_log', 'mad_log', 'ready', 'quality', 'n_eff'),
                         (toUInt8(1), en_uniq_dst_ips.1, 'uniq_dst_ips', slot),
                         (toFloat64(0), toFloat64(0), toUInt8(0), toFloat32(0), toUInt32(0)))   AS p1_uniq_dst_ips,
        dictGetOrDefault('isp.dict_bl_profile', ('shape_log', 'mad_log', 'ready', 'quality', 'n_eff'),
                         (toUInt8(0), '', 'uniq_dst_ips', slot),
                         (toFloat64(0), toFloat64(0), toUInt8(0), toFloat32(0), toUInt32(0)))   AS p0_uniq_dst_ips,
        dictGetOrDefault('isp.dict_bl_thresholds', ('offset_log', 'sigma_scale'),
                         ('anomaly.level_shift', 'uniq_dst_ips'),
                         (toFloat64(0), toFloat64(1)))                                          AS th_uniq_dst_ips,
        multiIf(p2_uniq_dst_ips.3 = 1 AND en_uniq_dst_ips.3 != 4, p2_uniq_dst_ips.1,
                p1_uniq_dst_ips.3 = 1 AND en_uniq_dst_ips.3 IN (2, 5), en_uniq_dst_ips.2 + p1_uniq_dst_ips.1,
                p0_uniq_dst_ips.3 = 1 AND en_uniq_dst_ips.3 IN (2, 5), en_uniq_dst_ips.2 + p0_uniq_dst_ips.1,
                CAST(nan, 'Float64'))                                                           AS mu_eff_uniq_dst_ips,
        greatest(1.4826 * multiIf(p2_uniq_dst_ips.3 = 1 AND en_uniq_dst_ips.3 != 4, p2_uniq_dst_ips.2,
                                  p1_uniq_dst_ips.3 = 1, p1_uniq_dst_ips.2,
                                  p0_uniq_dst_ips.2),
                 {mad_log_floor:Float64})                                                       AS sigma_hat_uniq_dst_ips,
        sigma_hat_uniq_dst_ips * th_uniq_dst_ips.2                                                          AS sigma_use_uniq_dst_ips,
        multiIf(p2_uniq_dst_ips.3 = 1 AND en_uniq_dst_ips.3 != 4, toUInt8(1),
                p1_uniq_dst_ips.3 = 1, toUInt8(2),
                p0_uniq_dst_ips.3 = 1, toUInt8(3),
                toUInt8(0))                                                                     AS level_used_uniq_dst_ips,
        multiIf(p2_uniq_dst_ips.3 = 1 AND en_uniq_dst_ips.3 != 4, p2_uniq_dst_ips.4,
                p1_uniq_dst_ips.3 = 1, p1_uniq_dst_ips.4 * 0.7,
                p0_uniq_dst_ips.4 * 0.5)                                                              AS quality_eff_uniq_dst_ips,
        (log1p(o.obs_uniq_dst_ips) - th_uniq_dst_ips.1 - mu_eff_uniq_dst_ips) / sigma_use_uniq_dst_ips                  AS z_uniq_dst_ips,
        -- ClickHouse no tiene expm1(): exp(x)-1 (E09 §4.6.5, baseline_value).
        exp(mu_eff_uniq_dst_ips + th_uniq_dst_ips.1) - 1                                                    AS exp_uniq_dst_ips,

        -- ═══ Resolución de jerarquía + z de uniq_dst_ports (E09 §4.6.5) ═══════════════
        dictGetOrDefault('isp.dict_bl_profile', ('mu_log', 'mad_log', 'ready', 'quality', 'n_eff'),
                         (o.entity_kind, o.entity_key, 'uniq_dst_ports', slot),
                         (toFloat64(0), toFloat64(0), toUInt8(0), toFloat32(0), toUInt32(0)))  AS p2_uniq_dst_ports,
        dictGetOrDefault('isp.dict_bl_entity', ('cohort', 'level_log', 'state', 'quality'),
                         (o.entity_kind, o.entity_key, 'uniq_dst_ports'),
                         ('unknown', toFloat64(0), toUInt8(0), toFloat32(0)))                   AS en_uniq_dst_ports,
        dictGetOrDefault('isp.dict_bl_profile', ('shape_log', 'mad_log', 'ready', 'quality', 'n_eff'),
                         (toUInt8(1), en_uniq_dst_ports.1, 'uniq_dst_ports', slot),
                         (toFloat64(0), toFloat64(0), toUInt8(0), toFloat32(0), toUInt32(0)))   AS p1_uniq_dst_ports,
        dictGetOrDefault('isp.dict_bl_profile', ('shape_log', 'mad_log', 'ready', 'quality', 'n_eff'),
                         (toUInt8(0), '', 'uniq_dst_ports', slot),
                         (toFloat64(0), toFloat64(0), toUInt8(0), toFloat32(0), toUInt32(0)))   AS p0_uniq_dst_ports,
        dictGetOrDefault('isp.dict_bl_thresholds', ('offset_log', 'sigma_scale'),
                         ('anomaly.level_shift', 'uniq_dst_ports'),
                         (toFloat64(0), toFloat64(1)))                                          AS th_uniq_dst_ports,
        multiIf(p2_uniq_dst_ports.3 = 1 AND en_uniq_dst_ports.3 != 4, p2_uniq_dst_ports.1,
                p1_uniq_dst_ports.3 = 1 AND en_uniq_dst_ports.3 IN (2, 5), en_uniq_dst_ports.2 + p1_uniq_dst_ports.1,
                p0_uniq_dst_ports.3 = 1 AND en_uniq_dst_ports.3 IN (2, 5), en_uniq_dst_ports.2 + p0_uniq_dst_ports.1,
                CAST(nan, 'Float64'))                                                           AS mu_eff_uniq_dst_ports,
        greatest(1.4826 * multiIf(p2_uniq_dst_ports.3 = 1 AND en_uniq_dst_ports.3 != 4, p2_uniq_dst_ports.2,
                                  p1_uniq_dst_ports.3 = 1, p1_uniq_dst_ports.2,
                                  p0_uniq_dst_ports.2),
                 {mad_log_floor:Float64})                                                       AS sigma_hat_uniq_dst_ports,
        sigma_hat_uniq_dst_ports * th_uniq_dst_ports.2                                                          AS sigma_use_uniq_dst_ports,
        multiIf(p2_uniq_dst_ports.3 = 1 AND en_uniq_dst_ports.3 != 4, toUInt8(1),
                p1_uniq_dst_ports.3 = 1, toUInt8(2),
                p0_uniq_dst_ports.3 = 1, toUInt8(3),
                toUInt8(0))                                                                     AS level_used_uniq_dst_ports,
        multiIf(p2_uniq_dst_ports.3 = 1 AND en_uniq_dst_ports.3 != 4, p2_uniq_dst_ports.4,
                p1_uniq_dst_ports.3 = 1, p1_uniq_dst_ports.4 * 0.7,
                p0_uniq_dst_ports.4 * 0.5)                                                              AS quality_eff_uniq_dst_ports,
        (log1p(o.obs_uniq_dst_ports) - th_uniq_dst_ports.1 - mu_eff_uniq_dst_ports) / sigma_use_uniq_dst_ports                  AS z_uniq_dst_ports,
        -- ClickHouse no tiene expm1(): exp(x)-1 (E09 §4.6.5, baseline_value).
        exp(mu_eff_uniq_dst_ports + th_uniq_dst_ports.1) - 1                                                    AS exp_uniq_dst_ports,

        -- ═══ Resolución de jerarquía + z de flows (E09 §4.6.5) ═══════════════
        dictGetOrDefault('isp.dict_bl_profile', ('mu_log', 'mad_log', 'ready', 'quality', 'n_eff'),
                         (o.entity_kind, o.entity_key, 'flows', slot),
                         (toFloat64(0), toFloat64(0), toUInt8(0), toFloat32(0), toUInt32(0)))  AS p2_flows,
        dictGetOrDefault('isp.dict_bl_entity', ('cohort', 'level_log', 'state', 'quality'),
                         (o.entity_kind, o.entity_key, 'flows'),
                         ('unknown', toFloat64(0), toUInt8(0), toFloat32(0)))                   AS en_flows,
        dictGetOrDefault('isp.dict_bl_profile', ('shape_log', 'mad_log', 'ready', 'quality', 'n_eff'),
                         (toUInt8(1), en_flows.1, 'flows', slot),
                         (toFloat64(0), toFloat64(0), toUInt8(0), toFloat32(0), toUInt32(0)))   AS p1_flows,
        dictGetOrDefault('isp.dict_bl_profile', ('shape_log', 'mad_log', 'ready', 'quality', 'n_eff'),
                         (toUInt8(0), '', 'flows', slot),
                         (toFloat64(0), toFloat64(0), toUInt8(0), toFloat32(0), toUInt32(0)))   AS p0_flows,
        dictGetOrDefault('isp.dict_bl_thresholds', ('offset_log', 'sigma_scale'),
                         ('anomaly.level_shift', 'flows'),
                         (toFloat64(0), toFloat64(1)))                                          AS th_flows,
        multiIf(p2_flows.3 = 1 AND en_flows.3 != 4, p2_flows.1,
                p1_flows.3 = 1 AND en_flows.3 IN (2, 5), en_flows.2 + p1_flows.1,
                p0_flows.3 = 1 AND en_flows.3 IN (2, 5), en_flows.2 + p0_flows.1,
                CAST(nan, 'Float64'))                                                           AS mu_eff_flows,
        greatest(1.4826 * multiIf(p2_flows.3 = 1 AND en_flows.3 != 4, p2_flows.2,
                                  p1_flows.3 = 1, p1_flows.2,
                                  p0_flows.2),
                 {mad_log_floor:Float64})                                                       AS sigma_hat_flows,
        sigma_hat_flows * th_flows.2                                                          AS sigma_use_flows,
        multiIf(p2_flows.3 = 1 AND en_flows.3 != 4, toUInt8(1),
                p1_flows.3 = 1, toUInt8(2),
                p0_flows.3 = 1, toUInt8(3),
                toUInt8(0))                                                                     AS level_used_flows,
        multiIf(p2_flows.3 = 1 AND en_flows.3 != 4, p2_flows.4,
                p1_flows.3 = 1, p1_flows.4 * 0.7,
                p0_flows.4 * 0.5)                                                              AS quality_eff_flows,
        (log1p(o.obs_flows) - th_flows.1 - mu_eff_flows) / sigma_use_flows                  AS z_flows,
        -- ClickHouse no tiene expm1(): exp(x)-1 (E09 §4.6.5, baseline_value).
        exp(mu_eff_flows + th_flows.1) - 1                                                    AS exp_flows,

        level_used_pps                                                        AS level_used_num,
        (quality_eff_pps + quality_eff_bps + quality_eff_uniq_dst_ips
            + quality_eff_uniq_dst_ports + quality_eff_flows) / 5             AS quality_avg
    FROM obs AS o
)
WHERE obs_pps >= {residual_min_pps:Float64} OR obs_uniq_dst_ips >= {residual_min_uniq_dst:UInt32}
ORDER BY obs_pps DESC
LIMIT {residual_max_entities:UInt32}
SETTINGS max_memory_usage = 2147483648, max_execution_time = 30;
